# Generated by Django 2.1.7 on 2019-02-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/job/%y/%m/%d')),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
    ]
