# Generated by Django 2.1.7 on 2019-02-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('send_date', models.DateTimeField()),
            ],
        ),
    ]
