# Generated by Django 2.1.7 on 2019-02-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_contactuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
